export const environment = {
	production: true,
	apiKey: "gHgHKRbIjdguCM4cv5481hdiF5hZGWZ4x12Ur-7v",
	baseUrl: "https://calendo.dav-apps.tech",
	version: "0.5",
	appId: 5,
	todoTableId: 10,
	appointmentTableId: 11,
	todoCompletedKey: "completed",
	todoTimeKey: "time",
	todoNameKey: "name",
	todoGroupsKey: "groups",
	appointmentNameKey: "name",
	appointmentStartKey: "start",
	appointmentEndKey: "end",
	appointmentAllDayKey: "allday",
	appointmentColorKey: "color",
	appointmentDefaultColor: "1565C0",
	notificationUuidKey: "notification_uuid",
	settingsSortTodosByDateKey: "settings-sortTodosByDate",
	settingsShowOldAppointments: "settings-showOldAppointments",
	visitKey: "visit"
};
