export const environment = {
	production: true,
	apiKey: "gHgHKRbIjdguCM4cv5481hdiF5hZGWZ4x12Ur-7v",
	baseUrl: "https://calendo.dav-apps.tech",
	version: "0.7.1",
   appId: 5,
   todoListTableId: 13,
	todoTableId: 10,
   appointmentTableId: 11,
   todoListNameKey: "name",
   todoListTimeKey: "time",
   todoListTodosKey: "todos",
   todoListTodoListsKey: "todo_lists",
   todoListGroupsKey: "groups",
   todoListListKey: "list",
	todoCompletedKey: "completed",
	todoTimeKey: "time",
	todoNameKey: "name",
   todoGroupsKey: "groups",
   todoListKey: "list",
	appointmentNameKey: "name",
	appointmentStartKey: "start",
	appointmentEndKey: "end",
	appointmentAllDayKey: "allday",
	appointmentColorKey: "color",
	appointmentDefaultColor: "1565C0",
	notificationUuidKey: "notification_uuid",
	visitKey: "visit",
	// Settings keys
   settingsSortTodosByDateKey: "settings-sortTodosByDate",
	settingsThemeKey: "settings-theme",
	// Settings defaults
	settingsSortTodosByDateDefault: true,
	settingsThemeDefault: "system",
	// Other constants
	lightThemeKey: "light",
	darkThemeKey: "dark",
	systemThemeKey: "system"
};
